spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///springbootjdbc
    driver-class-name: com.mysql.jdbc.Driver
